### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by dimonoid** [uorocketry/payload-code-2019#1]
I just wanted to join your team, but you don't seem to respond to my emails so I am writing in here. Please respond to (deleted)

**Comment by buzuloiu** [comment]
Hey! Sorry that we missed your email. Our first meeting of the year is coming up soon so it's the perfect time to join. 

I added your email to the list of new people on the team, you should get an email about where to go for the first meeting and when. The meeting will probably be this coming weekend. 

If you have any more questions feel free to message our page on facebook, that's usually where we reply the fastest https://www.facebook.com/uorocketry/
